module.exports = {
  apps: [
    {
      name: "opencode-server",
      script: "bunx",
      args: ["opencode-ai@latest", "web", "--port", "4096", "--hostname", "0.0.0.0"],
      cwd: "/workspace",
      env: {
        HOME: process.env.HOME || "/home/err",
        PM2_HOME: process.env.PM2_HOME || "/srv/opencode-stack-data/pm2",
        XDG_CONFIG_HOME: process.env.XDG_CONFIG_HOME || "/home/err/.config",
        XDG_DATA_HOME: process.env.XDG_DATA_HOME || "/home/err/.local/share",
        XDG_CACHE_HOME: process.env.XDG_CACHE_HOME || "/home/err/.cache",
        XDG_STATE_HOME: process.env.XDG_STATE_HOME || "/home/err/.local/state",
        OPENCODE_CONFIG_DIR: process.env.OPENCODE_CONFIG_DIR || "/workspace/.opencode",
        OPENCODE_SERVER_PASSWORD: process.env.OPENCODE_SERVER_PASSWORD || "",
        OPENCODE_SERVER_USERNAME: process.env.OPENCODE_SERVER_USERNAME || "opencode",
        OPENPLANNER_URL: process.env.OPENPLANNER_URL || "http://host.docker.internal:7777",
        OPENPLANNER_API_KEY: process.env.OPENPLANNER_API_KEY || "change-me",
        OPEN_HAX_OPENAI_PROXY_AUTH_TOKEN:
          process.env.OPEN_HAX_OPENAI_PROXY_AUTH_TOKEN || "change-me-open-hax-proxy-token",
        OLLAMA_URL: process.env.OLLAMA_URL || "http://host.docker.internal:8789",
        OLLAMA_BASE_URL: process.env.OLLAMA_BASE_URL || "http://host.docker.internal:8789",
      },
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 5000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "opencode-gateway",
      script: "bun",
      args: ["/usr/local/lib/opencode-stack/gateway.mjs"],
      cwd: "/workspace",
      env: {
        PM2_HOME: process.env.PM2_HOME || "/srv/opencode-stack-data/pm2",
        OPENCODE_GATEWAY_DATA_DIR: process.env.OPENCODE_GATEWAY_DATA_DIR || "/srv/opencode-stack-data",
        OPENCODE_GATEWAY_PUBLIC_PORT: process.env.OPENCODE_GATEWAY_PUBLIC_PORT || "4180",
        OPENCODE_GATEWAY_ADMIN_PORT: process.env.OPENCODE_GATEWAY_ADMIN_PORT || "4181",
        OPENCODE_UPSTREAM_URL: process.env.OPENCODE_UPSTREAM_URL || "http://127.0.0.1:4096",
        OPENCODE_GATEWAY_JANUS_URL: process.env.OPENCODE_GATEWAY_JANUS_URL || "http://mcp-stack:8788",
        ETA_MU_UPSTREAM_URL: process.env.ETA_MU_UPSTREAM_URL || "http://host.docker.internal:8787",
        ETA_MU_BASE_PATH: process.env.ETA_MU_BASE_PATH || "/eta-mu",
        OPENCODE_SERVER_PASSWORD: process.env.OPENCODE_SERVER_PASSWORD || "",
        OPENCODE_SERVER_USERNAME: process.env.OPENCODE_SERVER_USERNAME || "opencode",
        OAUTH_GITHUB_CLIENT_ID: process.env.OAUTH_GITHUB_CLIENT_ID || "",
        OAUTH_GITHUB_CLIENT_SECRET: process.env.OAUTH_GITHUB_CLIENT_SECRET || "",
        GITHUB_LOGIN_CLIENT_ID:
          process.env.GITHUB_LOGIN_CLIENT_ID || process.env.OAUTH_GITHUB_CLIENT_ID || "",
        GITHUB_LOGIN_CLIENT_SECRET:
          process.env.GITHUB_LOGIN_CLIENT_SECRET || process.env.OAUTH_GITHUB_CLIENT_SECRET || "",
        OAUTH_GITHUB_REDIRECT_URI: process.env.OAUTH_GITHUB_REDIRECT_URI || "",
        PUBLIC_BASE_URL: process.env.PUBLIC_BASE_URL || "",
        GITHUB_ALLOWED_USERS: process.env.GITHUB_ALLOWED_USERS || "",
      },
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 5000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
    },
  ],
};
