#!/usr/bin/env node
/**
 * Generate ClojureScript design token definitions.
 */

import { writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = join(__dirname, '..', 'dist');

// Import raw token values from compiled JS
const { tokenValues } = await import('../dist/index.js');

function toCljValue(value, indent = 0) {
  const pad = '  '.repeat(indent);
  const padInner = '  '.repeat(indent + 1);
  
  if (typeof value === 'string') {
    return `"${value}"`;
  }
  
  if (typeof value === 'number') {
    return String(value);
  }
  
  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value);
    if (entries.length === 0) return '{}';
    
    const pairs = entries.map(([k, v]) => {
      const cljKey = k.replace(/([A-Z])/g, '-$1').toLowerCase();
      return `:${cljKey} ${toCljValue(v, indent + 1)}`;
    });
    
    if (pairs.length === 1) {
      return `{${pairs[0]}}`;
    }
    
    return `{\n${padInner}${pairs.join(`\n${padInner}`)}\n${pad}}`;
  }
  
  return 'nil';
}

function generateCljsNamespace() {
  const lines = [
    ';; Auto-generated by generate-cljs.mjs - DO NOT EDIT',
    '(ns devel.ui.tokens',
    '  "Design tokens for devel UI components")',
    '',
  ];
  
  // Generate def for each top-level token category
  for (const [name, value] of Object.entries(tokenValues)) {
    const cljName = name.replace(/([A-Z])/g, '-$1').toLowerCase();
    lines.push(`(def ${cljName}`);
    lines.push(`  ${toCljValue(value, 1)})`);
    lines.push('');
  }
  
  return lines.join('\n');
}

try {
  mkdirSync(distDir, { recursive: true });
  const cljs = generateCljsNamespace();
  writeFileSync(join(distDir, 'tokens.cljs'), cljs);
  console.log('Generated dist/tokens.cljs');
} catch (err) {
  console.error('Failed to generate ClojureScript tokens:', err);
  process.exit(1);
}
