#!/usr/bin/env node
/**
 * Generate CSS custom properties from design tokens.
 */

import { writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = join(__dirname, '..', 'dist');

// Import raw token values from compiled JS
const { tokenValues } = await import('../dist/index.js');

function flattenObject(obj, prefix = '') {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    const cssVarName = prefix ? `${prefix}-${key}` : key;
    if (typeof value === 'string') {
      result[cssVarName] = value;
    } else if (typeof value === 'object' && value !== null) {
      Object.assign(result, flattenObject(value, cssVarName));
    }
  }
  return result;
}

function generateCssTokens() {
  const cssVars = flattenObject(tokenValues, 'token');
  const lines = [
    '/* Auto-generated by generate-css.mjs - DO NOT EDIT */',
    ':root {',
  ];
  
  for (const [name, value] of Object.entries(cssVars)) {
    lines.push(`  --${name}: ${value};`);
  }
  
  lines.push('}');
  return lines.join('\n');
}

try {
  mkdirSync(distDir, { recursive: true });
  const css = generateCssTokens();
  writeFileSync(join(distDir, 'tokens.css'), css);
  console.log('Generated dist/tokens.css');
} catch (err) {
  console.error('Failed to generate CSS tokens:', err);
  process.exit(1);
}
