module.exports = {
  reporter: ['text', 'json', 'html'],
  reportsDirectory: 'coverage/unit',
  exclude: [
    'coverage/**',
    'dist/**',
    'node_modules/**',
    '**/*.test.js',
    '**/*.test.ts',
    '**/*.spec.js',
    '**/*.spec.ts',
    '**/*.config.js',
    '**/*.config.mjs',
    '**/cli/**',
  ],
  include: [
    'packages/*/src/**/*.js',
    'packages/*/src/**/*.ts',
    'services/*/src/**/*.js',
    'services/*/src/**/*.ts',
  ],
  branches: 80,
  functions: 80,
  lines: 80,
  statements: 80,
  clean: true,
  skipFull: false,
  extension: ['.js', '.ts'],
};
