(ns promptbench.report.datasheet
  "Dataset datasheet generation (Gebru et al. 2021).

   Generates a Markdown datasheet following the Gebru et al. 2021 format
   with all 7 required sections:
   1. Motivation
   2. Composition
   3. Collection Process
   4. Preprocessing
   5. Uses
   6. Distribution
   7. Maintenance

   All sections are populated with actual build values — no placeholders.

   See validation contract VAL-METRIC-005."
  (:require [clojure.string :as str]
            [promptbench.taxonomy.registry :as taxonomy]
            [promptbench.pipeline.sources :as sources]))

;; ============================================================
;; Section Generators
;; ============================================================

(defn- motivation-section
  "Generate the Motivation section with actual build values."
  [{:keys [version]}]
  (str "## Motivation\n\n"
       "**Purpose:** This dataset was created to provide a reproducible, "
       "leakage-proof adversarial prompt evaluation benchmark for assessing "
       "LLM safety mechanisms. Unlike static benchmarks that decay over time, "
       "this dataset is generated via the Shibboleth DSL, making attack taxonomies, "
       "transform chains, and evaluation metrics first-class composable constructs.\n\n"
       "**Dataset Version:** " version "\n\n"
       "**Creators:** Generated by the Shibboleth generative DSL pipeline.\n\n"
       "**Funding:** This project is an open-source research contribution under GPL-3.0.\n\n"
       "**Intended Use:** Evaluation of LLM safety and alignment mechanisms against "
       "adversarial prompts across multiple languages and attack strategies.\n"))

(defn- composition-section
  "Generate the Composition section with actual build values."
  [{:keys [total-prompts total-variants languages splits seed]}]
  (let [families (sort (map name (keys (taxonomy/all-families))))
        lang-names (sort (map name languages))]
    (str "## Composition\n\n"
         "**Total canonical prompts:** " total-prompts "\n\n"
         "**Total transform variants:** " total-variants "\n\n"
         "**Languages:** " (str/join ", " lang-names) "\n\n"
         "**Attack families:** " (str/join ", " families) "\n\n"
         "**Split distribution:**\n"
         (str/join "\n"
                   (for [[split cnt] (sort-by key splits)]
                     (str "- " (name split) ": " cnt " prompts")))
         "\n\n"
         "**Build seed:** " seed "\n\n"
         "**Instance types:** Each instance is a text prompt (canonical or transformed) "
         "with associated metadata including source provenance, attack family classification, "
         "intent label, language, cluster assignment, and split membership.\n\n"
         "**Label types:** Intent labels (adversarial, benign, contested), "
         "attack family taxonomic classifications, harm category hierarchy.\n\n"
         "**Missing data:** No missing values in required fields (source_id, canonical_hash, "
         "canonical_text, canonical_lang, intent_label, split). Optional fields "
         "(attack_family, harm_category) may be absent for benign prompts.\n\n"
         "**Relationships:** Variant records link back to canonical prompts via source_id. "
         "Cluster assignments link prompts to their embedding-space neighborhoods. "
         "Splits are enforced at the cluster level to prevent leakage.\n\n"
         "**Confidentiality:** This dataset contains adversarial prompt examples intended "
         "for safety research. Content may include attempts to bypass safety mechanisms.\n")))

(defn- collection-process-section
  "Generate the Collection Process section with actual build values."
  [{:keys [sources-list]}]
  (let [source-descriptions
        (into []
              (keep (fn [src-name]
                      (when-let [src (sources/get-source src-name)]
                        (str "- **" (name src-name) "**: " (:description src)
                             " (version: " (:version src)
                             ", license: " (name (:license src)) ")"))))
              (sort sources-list))]
    (str "## Collection Process\n\n"
         "**Data sources:**\n"
         (if (seq source-descriptions)
           (str/join "\n" source-descriptions)
           "- Sources registered in the Shibboleth pipeline configuration")
         "\n\n"
         "**Collection methodology:** Prompts are collected from registered source datasets "
         "through the Shibboleth pipeline. Each source is fetched (Stage 0), "
         "canonicalized with NFKC normalization (Stage 1), embedded using "
         "sentence-transformers (Stage 2), clustered via HDBSCAN (Stage 2), "
         "and split with cluster-level disjointness (Stage 3).\n\n"
         "**Sampling strategy:** All prompts from registered sources are included. "
         "No subsampling is performed. Splits are determined by cluster-level "
         "stratified assignment to ensure no information leakage between train/dev/test.\n\n"
         "**Time frame:** Data is collected at build time from the configured sources. "
         "The build is fully reproducible given the same seed and source versions.\n\n"
         "**Ethical review:** This dataset is intended for safety evaluation research. "
         "Adversarial prompts are included to test model robustness, not to promote harmful content.\n")))

(defn- preprocessing-section
  "Generate the Preprocessing section with actual build values."
  [{:keys [total-prompts total-variants]}]
  (str "## Preprocessing\n\n"
       "**Text normalization:** NFKC Unicode normalization followed by whitespace "
       "collapse (all whitespace sequences replaced with single space, leading/trailing trimmed).\n\n"
       "**Hashing:** SHA-256 canonical hashes computed on normalized text for deduplication "
       "and provenance tracking.\n\n"
       "**Embedding:** Texts embedded using multilingual-e5-large sentence-transformer "
       "with L2 normalization.\n\n"
       "**Clustering:** HDBSCAN density-based clustering on embedding vectors. "
       "Noise points (cluster_id=-1) are treated as singleton clusters.\n\n"
       "**Splitting:** Cluster-level stratified splitting with enforced disjointness. "
       "No cluster appears in more than one split (train/dev/test).\n\n"
       "**Transform generation:** " total-variants " variants generated from "
       total-prompts " canonical prompts through machine translation, "
       "code-mixing, homoglyph substitution, and token exhaustion transforms. "
       "Transform application is guided by attack family affinity declarations.\n\n"
       "**Raw data preserved:** The pipeline stores intermediate artifacts at each stage "
       "with SHA-256 checksums and stage manifests for full reproducibility.\n"))

(defn- uses-section
  "Generate the Uses section."
  [_build-info]
  (str "## Uses\n\n"
       "**Intended uses:**\n"
       "- Evaluating LLM safety mechanisms against adversarial prompts\n"
       "- Benchmarking safety across languages and attack strategies\n"
       "- Measuring transform robustness (how safety degrades under obfuscation)\n"
       "- Computing SEU tradeoff curves for model/policy combinations\n\n"
       "**Not intended for:**\n"
       "- Training models to generate harmful content\n"
       "- Bypassing safety mechanisms in production systems\n"
       "- Any use that violates the GPL-3.0 license terms\n\n"
       "**Impact assessment:** This dataset enables safety researchers to evaluate "
       "model robustness against adversarial attacks. The adversarial examples are "
       "designed to test safety mechanisms, not to cause harm. Responsible use is expected.\n"))

(defn- distribution-section
  "Generate the Distribution section with actual build values."
  [{:keys [license version git-commit]}]
  (str "## Distribution\n\n"
       "**License:** " license "\n\n"
       "**Distribution format:** Reproducibility bundle containing Parquet data files, "
       "EDN manifests, SHA-256 checksums, and this datasheet.\n\n"
       "**Bundle contents:**\n"
       "- `prompts.parquet` — canonical prompt records (12-column schema)\n"
       "- `variants.parquet` — transform variant records\n"
       "- `manifests/` — per-stage manifests with checksums and provenance\n"
       "- `checksums.sha256` — file-level integrity checksums\n"
       "- `verification_report.edn` — post-build verification results\n"
       "- `build_manifest.edn` — top-level build metadata\n"
       "- `datasheet.md` — this document\n\n"
       "**Version control:** Build is tagged with git commit " git-commit
       " and version " version ".\n\n"
       "**Third-party restrictions:** Downstream use is governed by source dataset licenses "
       "and the project GPL-3.0 license.\n"))

(defn- maintenance-section
  "Generate the Maintenance section with actual build values."
  [{:keys [version seed]}]
  (str "## Maintenance\n\n"
       "**Maintainer:** The Shibboleth project maintainers.\n\n"
       "**Contact:** Via the project repository issue tracker.\n\n"
       "**Update process:** New attack families, transforms, or sources can be added "
       "by extending the DSL definitions and re-running the pipeline with the same seed (" seed
       ") for backward-compatible updates, or a new seed for fresh builds.\n\n"
       "**Versioning:** Dataset version " version ". "
       "The pipeline is designed for deterministic rebuilds — running with the same "
       "seed and source versions produces byte-identical output.\n\n"
       "**Erratum process:** Issues discovered post-build are tracked in the project "
       "repository. Corrections trigger a version increment and full rebuild.\n\n"
       "**Deprecation:** Previous versions remain accessible in the git history. "
       "The build manifest and checksums enable verification of any historical build.\n"))

;; ============================================================
;; Main Generation Function
;; ============================================================

(defn generate-datasheet
  "Generate a complete Gebru et al. 2021 datasheet as a Markdown string.

   build-info — map with keys:
     :version         — string pipeline version
     :seed            — integer build seed
     :total-prompts   — integer count of canonical prompts
     :total-variants  — integer count of transform variants
     :languages       — vector of language keywords
     :sources         — vector of source keywords
     :license         — string license name
     :git-commit      — string git commit hash
     :splits          — map of split-kw -> count

   Returns a Markdown string with all 7 Gebru sections populated
   with actual build values."
  [build-info]
  (let [info (assoc build-info :sources-list (:sources build-info))]
    (str "# Dataset Datasheet\n\n"
         "_Generated by Shibboleth v" (:version build-info) " — "
         "Gebru et al. 2021 format_\n\n"
         "---\n\n"
         (motivation-section info)
         "\n---\n\n"
         (composition-section info)
         "\n---\n\n"
         (collection-process-section info)
         "\n---\n\n"
         (preprocessing-section info)
         "\n---\n\n"
         (uses-section info)
         "\n---\n\n"
         (distribution-section info)
         "\n---\n\n"
         (maintenance-section info))))
