#!/usr/bin/env node
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');
const distDir = join(repoRoot, 'dist');
const { tokenValues } = await import('../dist/tokens/src/index.js');

function toCljValue(value, indent = 0) {
  const pad = '  '.repeat(indent);
  const padInner = '  '.repeat(indent + 1);
  if (typeof value === 'string') return `"${value}"`;
  if (typeof value === 'number') return String(value);
  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value);
    if (entries.length === 0) return '{}';
    const pairs = entries.map(([k, v]) => {
      const cljKey = k.replace(/([A-Z])/g, '-$1').toLowerCase();
      return `:${cljKey} ${toCljValue(v, indent + 1)}`;
    });
    if (pairs.length === 1) return `{${pairs[0]}}`;
    return `{\n${padInner}${pairs.join(`\n${padInner}`)}\n${pad}}`;
  }
  return 'nil';
}

const lines = [
  ';; Auto-generated by generate-cljs.mjs - DO NOT EDIT',
  '(ns devel.ui.tokens',
  '  "Design tokens for Open Hax UXX components")',
  ''
];
for (const [name, value] of Object.entries(tokenValues || {})) {
  if (!name || value === undefined || value === null) continue;
  const cljName = name.replace(/([A-Z])/g, '-$1').toLowerCase();
  lines.push(`(def ${cljName}`);
  lines.push(`  ${toCljValue(value, 1)})`);
  lines.push('');
}
mkdirSync(distDir, { recursive: true });
writeFileSync(join(distDir, 'tokens.cljs'), `${lines.join('\n')}\n`);
console.log('Generated dist/tokens.cljs');
