#!/usr/bin/env node
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');
const distDir = join(repoRoot, 'dist');
const { tokenValues, themePacks, getThemeCssVars } = await import('../dist/tokens/src/index.js');

function flattenObject(obj, prefix = '') {
  const result = {};
  if (!obj || typeof obj !== 'object') return result;
  for (const [key, value] of Object.entries(obj)) {
    if (typeof key !== 'string') continue;
    const cssVarName = prefix ? `${prefix}-${key}` : key;
    if (typeof value === 'string') {
      result[cssVarName] = value;
    } else if (value && typeof value === 'object' && !Array.isArray(value)) {
      Object.assign(result, flattenObject(value, cssVarName));
    }
  }
  return result;
}

const legacyCssVars = flattenObject(tokenValues, 'token');
const defaultThemeCssVars = getThemeCssVars(themePacks.monokai);
const lines = [
  '/* Auto-generated by generate-css.mjs - DO NOT EDIT */',
  ':root, [data-uxx-theme="monokai"] {',
];
for (const [name, value] of Object.entries(legacyCssVars)) {
  lines.push(`  --${name}: ${value};`);
}
for (const [name, value] of Object.entries(defaultThemeCssVars)) {
  lines.push(`  ${name}: ${value};`);
}
lines.push('}');

for (const [themeName, themePack] of Object.entries(themePacks)) {
  if (themeName === 'monokai') continue;
  lines.push(`[data-uxx-theme="${themeName}"] {`);
  const themeCssVars = getThemeCssVars(themePack);
  for (const [name, value] of Object.entries(themeCssVars)) {
    lines.push(`  ${name}: ${value};`);
  }
  lines.push('}');
}

mkdirSync(distDir, { recursive: true });
writeFileSync(join(distDir, 'tokens.css'), `${lines.join('\n')}\n`);
console.log('Generated dist/tokens.css');
