(ns devel.ui.primitives.core
  "Public Reagent exports backed by the canonical React implementation."
  (:require [devel.ui.react-interop :as interop]))

(def theme-provider interop/theme-provider)
(def toast-provider interop/toast-provider)
(def entity-card interop/entity-card)

(def button interop/button)
(def badge interop/badge)
(def spinner interop/spinner)
(def card interop/card)
(def card-header interop/card-header)
(def card-body interop/card-body)
(def card-footer interop/card-footer)
(def modal interop/modal)
(def modal-header interop/modal-header)
(def modal-body interop/modal-body)
(def modal-footer interop/modal-footer)
(def tooltip interop/tooltip)
(def input interop/input)
(def select interop/select)
(def textarea interop/textarea)
(def progress interop/progress)
(def resizable-pane interop/resizable-pane)
(def which-key-popup interop/which-key-popup)
(def inspector-pane interop/inspector-pane)
(def context-section interop/context-section)
(def pinned-tabs-bar interop/pinned-tabs-bar)
(def permission-card interop/permission-card)
(def prompt-card interop/prompt-card)
(def permission-prompts interop/permission-prompts)
(def react-reagent-seam interop/react-reagent-seam)
(def command-palette interop/command-palette)
(def chat interop/chat)
(def toast interop/toast)
(def file-tree interop/file-tree)
(def tabs interop/tabs)
(def searchable-select interop/searchable-select)
(def collapsible-panel interop/collapsible-panel)
(def key-value-section interop/key-value-section)
(def surface-hero interop/surface-hero)
(def panel-header interop/panel-header)
(def metric-tile interop/metric-tile)
(def metric-tile-grid interop/metric-tile-grid)
(def filter-toolbar interop/filter-toolbar)
(def action-strip interop/action-strip)
(def status-chip-stack interop/status-chip-stack)
(def data-table-shell interop/data-table-shell)
(def pagination interop/pagination)
(def feed interop/feed)
(def markdown interop/markdown)
(def code-block interop/code-block)
(def diff-viewer interop/diff-viewer)
(def markdown-editor interop/markdown-editor)
(def rich-text-editor interop/rich-text-editor)

(def use-toast interop/use-toast)
(def use-adapter interop/use-adapter)
(def use-uxx-theme interop/use-uxx-theme)
(def use-resolved-theme interop/use-resolved-theme)
(def use-theme-name interop/use-theme-name)
(def paginate-items interop/paginate-items)
(def calculate-total-pages interop/calculate-total-pages)

(def components interop/components)
(def providers interop/providers)
(def hooks interop/hooks)
(def utilities interop/utilities)
