apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: proxx
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: proxx
      app.kubernetes.io/managed-by: kustomize
resources:
  - namespace.yaml
  - postgres-headless-service.yaml
  - postgres-service.yaml
  - proxx-data-pvc.yaml
  - proxx-api-service.yaml
  - proxx-web-service.yaml
  - proxx-deployment.yaml
  - proxx-postgres-statefulset.yaml
  - proxx-pdb.yaml