apiVersion: v1
kind: Service
metadata:
  name: proxx-postgres
spec:
  selector:
    app.kubernetes.io/name: proxx
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres