apiVersion: v1
kind: Service
metadata:
  name: proxx-api
spec:
  selector:
    app.kubernetes.io/name: proxx
    app.kubernetes.io/component: proxy
  ports:
    - name: http
      port: 8789
      targetPort: api