apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: proxx
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: proxx
      app.kubernetes.io/component: proxy