export type UiBackendTestKind =
  | "unit"
  | "api-client"
  | "component-integration"
  | "ava-puppeteer-e2e"
  | "backend-route-contract"
  | "ws-contract";

export interface UiBackendTestStub {
  kind: UiBackendTestKind;
  name: string;
  priority: "P0" | "P1" | "P2";
  assertion: string;
  status?: "planned" | "implemented";
  implementedBy?: string[];
}

export interface UiBackendSurface {
  id: string;
  route: string;
  owner: "tsx" | "cljs" | "mixed";
  surface: string;
  backend: string[];
  behavior: string[];
  stubs: UiBackendTestStub[];
}

export const uiBackendSurfaceMatrix: UiBackendSurface[] = [
  {
    id: "auth-boundary-login-signup-logout",
    route: "all routes, /login, /signup",
    owner: "mixed",
    surface: "AuthBoundary, LoginPage, SignupPage, shell user menu",
    backend: [
      "GET /api/auth/context",
      "GET /api/auth/config",
      "POST /api/auth/invite/redeem",
      "POST /api/auth/signup",
      "POST /api/auth/logout",
    ],
    behavior: [
      "Boot loads auth context before protected surfaces mount.",
      "Unauthenticated users see login or signup instead of protected content.",
      "Login configuration hides unavailable providers and invite redemption refreshes auth state.",
      "Logout clears user state and returns to unauthenticated rendering.",
    ],
    stubs: [
      {
        kind: "component-integration",
        priority: "P0",
        name: "renders login on 401 auth context",
        assertion: "mock /api/auth/context as 401 and assert LazyLoginPage appears",
        status: "implemented",
        implementedBy: ["frontend/src/pages/AuthContext.test.tsx"],
      },
      {
        kind: "component-integration",
        priority: "P0",
        name: "refreshes auth after invite redemption",
        assertion: "submit invite token, assert /api/auth/invite/redeem then /api/auth/context are called",
        status: "implemented",
        implementedBy: ["frontend/src/pages/AuthContext.test.tsx"],
      },
      { kind: "ava-puppeteer-e2e", priority: "P1", name: "logout returns shell to login", assertion: "authenticated fixture opens user menu, clicks sign out, asserts login surface" },
    ],
  },
  {
    id: "chat-workspace-main-runtime",
    route: "/",
    owner: "tsx",
    surface: "ChatPage / ChatWorkspacePane / ChatMainPane / ChatRuntimePanel",
    backend: [
      "GET /api/config",
      "GET /api/proxx/models",
      "GET /api/tools/catalog",
      "GET /api/knoxx/agents/catalog",
      "POST /api/knoxx/chat/start",
      "POST /api/knoxx/direct/start",
      "GET /api/knoxx/session/status",
      "GET /api/knoxx/run/:runId/events",
      "WS /ws/stream",
      "POST /api/knoxx/steer",
      "POST /api/knoxx/follow-up",
      "POST /api/knoxx/abort",
      "POST /api/knoxx/session/undo",
      "POST /api/shibboleth/handoff",
    ],
    behavior: [
      "Initial config hydrates role, actor, model, and tool affordances.",
      "Sending a message creates or resumes a session and then consumes streaming updates.",
      "Runtime panel surfaces status, run events, witness thread, and receipt river state.",
      "Abort, steer, follow-up, undo, and handoff mutate the active conversation safely.",
    ],
    stubs: [
      {
        kind: "unit",
        priority: "P0",
        name: "chat controller keeps session identifiers monotonic",
        assertion: "simulate queued response and run hydration; assert conversation/session/run ids persist",
        status: "implemented",
        implementedBy: ["frontend/src/components/chat-page/chat-runtime-actions.test.ts"],
      },
      {
        kind: "component-integration",
        priority: "P0",
        name: "send message calls chat start and renders queued state",
        assertion: "mock /api/knoxx/chat/start and assert pending assistant turn plus UI queued state",
        status: "implemented",
        implementedBy: [
          "frontend/src/components/chat-page/chat-runtime-actions.test.ts",
          "frontend/src/components/chat-page/ChatMainPane.test.tsx",
        ],
      },
      {
        kind: "ws-contract",
        priority: "P0",
        name: "stream deltas collapse to one final assistant message",
        assertion: "feed overlapping WS deltas and assert UI text is not duplicated",
        status: "implemented",
        implementedBy: ["frontend/src/components/chat-page/utils.test.ts"],
      },
      { kind: "ava-puppeteer-e2e", priority: "P1", name: "chat can start, stream, abort, and recover", assertion: "browser fixture sends message, observes stream, aborts, then sends a follow-up" },
    ],
  },
  {
    id: "chat-context-browser-scratchpad",
    route: "/ and embedded ChatWorkspacePane surfaces",
    owner: "tsx",
    surface: "ContextBar, ChatWorkspaceSidebar, WorkspaceBrowserCard, scratchpad actions",
    backend: [
      "GET /api/memory/sessions",
      "GET /api/memory/sessions/:sessionId",
      "POST /api/memory/search",
      "GET /api/documents/content/:path",
      "GET /api/ingestion/browse",
      "GET /api/ingestion/file",
      "POST /api/ingestion/search",
      "POST /api/cms/documents",
      "POST /api/data/op/labels/records/:recordId/reaction",
    ],
    behavior: [
      "Context explorer lists sessions, files, and semantic hits without blocking chat input.",
      "Pinned context and scratchpad state survive reload via local storage keys.",
      "Workspace file reads and CMS document creation handle success and backend errors.",
    ],
    stubs: [
      { kind: "unit", priority: "P1", name: "workspace actions normalize browse/search/file responses", assertion: "exercise workspace-actions with success, empty, and error payloads" },
      { kind: "component-integration", priority: "P1", name: "pinning a file injects context into the controller", assertion: "mock browse/file endpoints and assert pinned context item appears" },
      { kind: "ava-puppeteer-e2e", priority: "P2", name: "context explorer opens file and creates scratchpad CMS doc", assertion: "browser selects file, pins it, saves scratchpad, and observes POST /api/cms/documents" },
    ],
  },
  {
    id: "chat-voice-and-multimodal",
    route: "/ and embedded ChatWorkspacePane surfaces",
    owner: "tsx",
    surface: "VoiceInputButton, VoiceReplyButton, ConversationVoiceButton, MultimodalInput",
    backend: [
      "POST /api/voice/stt",
      "POST /api/voice/tts",
      "GET /api/workspace-media/raw",
      "POST /api/knoxx/chat/start with contentParts",
    ],
    behavior: [
      "Recorded audio posts multipart STT and inserts transcript into the composer.",
      "Assistant messages synthesize TTS blobs and expose playable audio.",
      "Attachments become content parts and raw workspace-media URLs render safely.",
    ],
    stubs: [
      { kind: "component-integration", priority: "P1", name: "STT success inserts transcript and STT failure shows retryable error", assertion: "mock MediaRecorder and /api/voice/stt for success/failure" },
      { kind: "component-integration", priority: "P1", name: "TTS returns blob and attaches audio controls", assertion: "mock /api/voice/tts as audio blob and assert object URL cleanup" },
      { kind: "unit", priority: "P1", name: "multimodal attachments normalize file/image parts", assertion: "assert contentParts payload uses expected type/url/text shape" },
    ],
  },
  {
    id: "mail-actor-mailbox",
    route: "/mail",
    owner: "tsx",
    surface: "MailPage inbox/outbox cards",
    backend: [
      "GET /api/actors/mailbox?box=&status=&limit=100",
      "POST /api/actors/mailbox/:mailboxId/ack",
    ],
    behavior: [
      "Inbox/outbox and status filters reload mailbox entries.",
      "Entry cards link to agent audit sessions, runs, and events when references are present.",
      "Acknowledging an inbox item posts ack then refreshes the list.",
    ],
    stubs: [
      {
        kind: "component-integration",
        priority: "P1",
        name: "filters mailbox entries by box and status",
        assertion: "change select/buttons and assert query params",
        status: "implemented",
        implementedBy: ["frontend/src/pages/MailPage.test.tsx"],
      },
      {
        kind: "component-integration",
        priority: "P1",
        name: "acknowledge posts ack and refreshes",
        assertion: "click Acknowledge and assert ack endpoint then mailbox reload",
        status: "implemented",
        implementedBy: ["frontend/src/pages/MailPage.test.tsx"],
      },
      { kind: "ava-puppeteer-e2e", priority: "P2", name: "mail links navigate into audit/events surfaces", assertion: "fixture entry with run/session/event refs exposes working links" },
    ],
  },
  {
    id: "studio-audio-library-playlists-labels",
    route: "/studio",
    owner: "tsx",
    surface: "BroadcastStudioPage audio browser, player, labels, playlist queue",
    backend: [
      "GET /api/studio/audio-library",
      "POST /api/studio/audio-library/ensure-dir",
      "POST /api/studio/audio-library/rename",
      "GET /api/studio/stream",
      "GET/PUT /api/studio/playlist",
      "POST /api/studio/save-m3u",
      "GET /api/studio/load-m3u",
      "GET /api/studio/playlists",
      "GET /api/studio/labels",
      "POST /api/studio/labels/add",
      "POST /api/studio/labels/remove",
      "GET /api/studio/labels/by-label",
      "POST /api/studio/sync-symlinks",
      "GET/POST /api/studio/audio-asset",
    ],
    behavior: [
      "Audio library browsing, folder creation, rename, stream playback, and playlist persistence stay in sync.",
      "Labels mutate the selected file and refresh label/filter views.",
      "Waveform/spectrogram assets save and reload without corrupting playback state.",
    ],
    stubs: [
      {
        kind: "component-integration",
        priority: "P0",
        name: "loads audio library and plays selected file stream URL",
        assertion: "mock audio library and assert audio src uses /api/studio/stream path",
        status: "implemented",
        implementedBy: ["frontend/src/pages/BroadcastStudioPage.test.tsx"],
      },
      {
        kind: "component-integration",
        priority: "P1",
        name: "playlist save/load round-trips queue items",
        assertion: "queue two files, save, reload fixture playlist, assert order",
        status: "implemented",
        implementedBy: ["frontend/src/pages/BroadcastStudioPage.test.tsx"],
      },
      {
        kind: "component-integration",
        priority: "P1",
        name: "label add/remove refreshes selected file labels",
        assertion: "mock label endpoints and assert chip list updates",
        status: "implemented",
        implementedBy: ["frontend/src/pages/BroadcastStudioPage.test.tsx"],
      },
      { kind: "ava-puppeteer-e2e", priority: "P2", name: "studio playback queue survives route reload", assertion: "browser fixture saves studio state then reloads /studio" },
    ],
  },
  {
    id: "studio-graph-cms-actions-and-scans",
    route: "/studio",
    owner: "tsx",
    surface: "BroadcastStudioPage graph labels, CMS draft actions, Discord import scans, contract ui-actions",
    backend: [
      "GET/POST /api/openplanner/v1/graph/labels",
      "POST /api/openplanner/v1/graph/edges/query",
      "GET /api/ingestion/audio-context",
      "GET/POST /api/openplanner/v1/cms/documents",
      "GET /api/openplanner/v1/gardens",
      "GET /api/contracts/ui-actions",
      "POST /api/studio/discord-audio-scan",
      "POST /api/studio/discord-image-scan",
    ],
    behavior: [
      "Studio can use graph labels and edges to organize audio and prompt context.",
      "CMS/garden actions create or publish studio-adjacent documents.",
      "Discord audio/image scans expose counts, manifest paths, and partial failures.",
    ],
    stubs: [
      { kind: "component-integration", priority: "P1", name: "loads contract ui-actions and renders allowed studio actions", assertion: "mock ui-actions and assert action buttons appear/disable by response" },
      { kind: "component-integration", priority: "P1", name: "discord scan surfaces count summary and failures", assertion: "mock scan response with skipped/failed counts and assert report row" },
      { kind: "backend-route-contract", priority: "P2", name: "audio context response contains transcript/chroma/context fields expected by composer", assertion: "contract test validates /api/ingestion/audio-context fixture schema" },
    ],
  },
  {
    id: "cms-workbench-documents-publish",
    route: "/cms",
    owner: "tsx",
    surface: "CmsPage workspace browser, CMS document editor, templates, publish workflow",
    backend: [
      "GET /api/ingestion/browse",
      "GET/PUT /api/ingestion/file",
      "POST /api/ingestion/search",
      "GET /api/ingestion/sources",
      "GET /api/ingestion/jobs",
      "GET/POST/PATCH /api/openplanner/v1/cms/documents",
      "POST/DELETE /api/openplanner/v1/cms/publish/:docId/:gardenId",
      "GET /api/openplanner/v1/gardens",
      "GET /api/memory/sessions",
      "GET /api/studio/stream",
    ],
    behavior: [
      "CMS loads workspace files, templates, gardens, ingestion sources/jobs, and CMS documents independently.",
      "Draft creation/update writes both OpenPlanner CMS documents and optional workspace files.",
      "Publish toggles garden membership and reflects published state.",
    ],
    stubs: [
      {
        kind: "component-integration",
        priority: "P0",
        name: "loads documents and opens selected CMS document",
        assertion: "mock document list/detail and assert editor fields hydrate",
        status: "implemented",
        implementedBy: ["frontend/src/pages/CmsPage.test.tsx"],
      },
      {
        kind: "component-integration",
        priority: "P0",
        name: "save existing document uses PATCH and preserves doc id",
        assertion: "edit title/body, click save, assert PATCH payload and notice",
        status: "implemented",
        implementedBy: ["frontend/src/pages/CmsPage.test.tsx"],
      },
      {
        kind: "component-integration",
        priority: "P1",
        name: "publish toggle POSTs and DELETEs selected garden relation",
        assertion: "toggle publish twice and assert methods/endpoints",
        status: "implemented",
        implementedBy: ["frontend/src/pages/CmsPage.test.tsx"],
      },
      { kind: "ava-puppeteer-e2e", priority: "P2", name: "CMS draft from workspace file can be edited and published", assertion: "browser opens file, creates doc, selects garden, publishes" },
    ],
  },
  {
    id: "visual-cms-editor",
    route: "/cms/editor/*",
    owner: "tsx",
    surface: "VisualCmsEditorPage",
    backend: [
      "GET /api/ingestion/file?path=:draft/view-contract.edn",
      "GET /api/ingestion/file?path=:draft/content.md",
      "PUT /api/ingestion/file",
    ],
    behavior: [
      "Editor reads view contract and markdown content from a draft path.",
      "Save writes the edited content back to ingestion file API.",
      "Missing draft files render actionable errors without losing local edits.",
    ],
    stubs: [
      {
        kind: "component-integration",
        priority: "P1",
        name: "loads visual draft files and renders editor",
        assertion: "mock contract/content file reads and assert rendered blocks",
        status: "implemented",
        implementedBy: ["frontend/src/pages/VisualCmsEditorPage.test.tsx"],
      },
      {
        kind: "component-integration",
        priority: "P1",
        name: "save writes markdown content to correct path",
        assertion: "edit content and assert PUT /api/ingestion/file payload",
        status: "implemented",
        implementedBy: ["frontend/src/pages/VisualCmsEditorPage.test.tsx"],
      },
    ],
  },
  {
    id: "contracts-page-admin-editor",
    route: "/contracts",
    owner: "tsx",
    surface: "ContractsPage TS editor with runtime side panel and chat",
    backend: [
      "GET /api/admin/contracts?kind=:class",
      "GET /api/admin/contracts/:id?kind=:class",
      "POST /api/admin/contracts/validate",
      "PUT /api/admin/contracts/:id",
      "POST /api/admin/contracts/:id/copy",
      "GET /api/admin/config/events",
      "POST /api/admin/triggers/:id/fire",
      "ChatWorkspacePane backend set from chat-workspace-main-runtime",
    ],
    behavior: [
      "Contract class filters load lists and selecting an item hydrates EDN plus structured fields.",
      "Validate and save send current EDN and update validation/errors/notices.",
      "Copy creates a new contract id and refreshes list without overwriting source.",
      "Runtime side panel maps triggers/jobs to selected contract and can fire triggers.",
    ],
    stubs: [
      {
        kind: "component-integration",
        priority: "P0",
        name: "class switch reloads list and clears stale selected contract",
        assertion: "switch agents/triggers and assert correct kind query and selection state",
        status: "implemented",
        implementedBy: ["frontend/src/pages/ContractsPage.test.tsx"],
      },
      {
        kind: "component-integration",
        priority: "P0",
        name: "validate/save posts current EDN",
        assertion: "edit EDN, click validate and save, assert endpoint payloads",
        status: "implemented",
        implementedBy: ["frontend/src/pages/ContractsPage.test.tsx"],
      },
      {
        kind: "component-integration",
        priority: "P1",
        name: "copy contract posts new id and focuses returned contract",
        assertion: "enter new id, copy, assert POST /copy and refreshed list",
        status: "implemented",
        implementedBy: ["frontend/src/pages/ContractsPage.test.tsx"],
      },
      { kind: "ava-puppeteer-e2e", priority: "P1", name: "contract editor save/validate works in browser", assertion: "existing AVA-style fixture covers edit id, check, save, request payloads" },
    ],
  },
  {
    id: "agents-contracts-tab-cljs-editor",
    route: "/agents?tab=contracts",
    owner: "cljs",
    surface: "shadow-cljs AgentsPage contracts tab",
    backend: [
      "GET /api/admin/contracts?kind=agents|roles|triggers|pipelines",
      "GET /api/admin/contracts/:id?kind=agents",
      "POST /api/admin/contracts/validate",
      "PUT /api/admin/contracts/:id",
      "GET /api/admin/config/events",
      "POST /api/admin/triggers/:id/fire",
    ],
    behavior: [
      "Agent list, editor draft, EDN, roles, triggers, and schedules are owned by CLJS state.",
      "Selected agent drives side-panel selected triggers and all-trigger partitioning.",
      "Validate/save bridge the CLJS editor state through TS API mocks without losing selected agent.",
    ],
    stubs: [
      { kind: "ava-puppeteer-e2e", priority: "P0", name: "CLJS contract editor validates and saves edited id", assertion: "implemented harness edits Contract id, clicks Check/Save, verifies request logs" },
      { kind: "ava-puppeteer-e2e", priority: "P1", name: "new agent button initializes draft and no stale triggers", assertion: "click plus, assert default draft id/fields and empty selected triggers" },
      { kind: "component-integration", priority: "P1", name: "trigger projection maps pipelines and agent targets", assertion: "CLJS pure helper test for trigger-schedule-jobs and selected-runtime-jobs" },
    ],
  },
  {
    id: "agents-audit-tab-chat-viewer",
    route: "/agents?tab=audit",
    owner: "mixed",
    surface: "AgentsPage audit tab, AgentAuditSessionList, ChatWorkspacePane",
    backend: [
      "GET /api/admin/contracts?kind=agents",
      "GET /api/admin/agents/active",
      "GET /api/memory/sessions",
      "GET /api/memory/sessions/:sessionId",
      "GET /api/admin/config/events",
      "ChatWorkspacePane backend set from chat-workspace-main-runtime",
    ],
    behavior: [
      "Active runs and memory sessions merge into one side-panel list with active-first ordering.",
      "Selected contract filters sessions and selected trigger cards.",
      "Selecting history resumes transcript into ChatWorkspacePane instead of legacy timeline.",
    ],
    stubs: [
      {
        kind: "unit",
        priority: "P0",
        name: "mergeAuditSessions dedupes active/history and computes status",
        assertion: "pure helper tests cover active, completed, failed, missing ids",
        status: "implemented",
        implementedBy: ["frontend/src/components/agent-audit/AgentAuditSessionList.test.tsx"],
      },
      {
        kind: "component-integration",
        priority: "P0",
        name: "session list loads active/history and filters selected contract",
        assertion: "mock active/memory endpoints and assert cards update on prop change",
        status: "implemented",
        implementedBy: ["frontend/src/components/agent-audit/AgentAuditSessionList.test.tsx"],
      },
      {
        kind: "ava-puppeteer-e2e",
        priority: "P0",
        name: "audit session resumes historical transcript into chat pane",
        assertion: "implemented harness clicks history card and asserts chat messages",
        status: "implemented",
        implementedBy: ["frontend/src/e2e/knoxx/frontend/e2e/ava_runner.cljs"],
      },
    ],
  },
  {
    id: "events-runtime-control-workbench",
    route: "/events",
    owner: "cljs",
    surface: "EventsPage CLJS workbench, EventAgentsPanel, AgentAuditLogs, Events Chat",
    backend: [
      "GET /api/admin/tools",
      "GET/PUT /api/admin/config/events",
      "POST /api/admin/config/events/jobs/:id/run",
      "POST /api/admin/config/events/dispatch",
      "POST /api/admin/config/events/runtime/start",
      "POST /api/admin/config/events/runtime/stop",
      "POST /api/admin/config/events/runtime/reset",
      "GET /api/admin/agents/active",
      "GET /api/memory/sessions",
      "ChatWorkspacePane backend set from chat-workspace-main-runtime",
    ],
    behavior: [
      "Permission gates hide runtime control and tool catalog unless allowed.",
      "Runtime jobs can be selected, reviewed, manually run, and pinned into chat context.",
      "Dispatch/start/stop/reset actions update runtime state and audit logs.",
    ],
    stubs: [
      { kind: "component-integration", priority: "P0", name: "permission denied hides EventAgentsPanel controls", assertion: "auth fixture lacks org.event_agents.control and asserts locked state" },
      { kind: "component-integration", priority: "P0", name: "manual run dispatches job id and refreshes runtime", assertion: "click run job and assert POST /jobs/:id/run then reload control" },
      { kind: "ava-puppeteer-e2e", priority: "P1", name: "events workbench dispatch/start/stop/reset happy path", assertion: "browser fixture executes runtime controls and asserts status transitions" },
    ],
  },
  {
    id: "data-overview-sources-services",
    route: "/data, /data/overview, /data/sources, /data/services",
    owner: "tsx",
    surface: "DataPage overview, sources, services tabs",
    backend: [
      "GET /api/ingestion/sources",
      "GET /api/ingestion/jobs",
      "POST /api/ingestion/jobs",
      "POST /api/ingestion/jobs/:jobId/cancel",
      "GET /api/data/health",
      "POST /api/data/jobs/build-semantic-edges",
      "POST /api/data/jobs/build-semantic-edges/incremental",
      "GET /api/data/op/v1/graph/embedding-coverage",
    ],
    behavior: [
      "Overview polls sources, jobs, service health, and embedding coverage.",
      "Sources/services can trigger or cancel ingestion and semantic edge jobs.",
      "Partial backend failures degrade individual cards without blanking the whole page.",
    ],
    stubs: [
      { kind: "component-integration", priority: "P0", name: "overview renders partial data when one service fails", assertion: "one Promise rejects and cards still render fulfilled services" },
      { kind: "component-integration", priority: "P1", name: "sync source posts ingestion job and refreshes", assertion: "click sync, assert POST /api/ingestion/jobs and subsequent GETs" },
      { kind: "backend-route-contract", priority: "P1", name: "ingestion job response schema includes id/status/source", assertion: "route contract validates UI-required fields" },
    ],
  },
  {
    id: "data-files-documents-graph-labels",
    route: "/data/files, /data/documents, /data/graph, /data/labels",
    owner: "tsx",
    surface: "DataPage file explorer, documents search, graph explorer, labels tab",
    backend: [
      "GET /api/ingestion/browse",
      "GET /api/ingestion/file",
      "GET /api/data/op/documents",
      "GET /api/graph/export",
      "GET/POST/PATCH/DELETE /api/openplanner/v1/graph/labels",
      "GET /api/openplanner/v1/graph/labels/:id/nodes",
      "POST /api/openplanner/v1/graph/labels/:id/apply",
      "POST /api/openplanner/v1/graph/labels/:id/remove",
    ],
    behavior: [
      "Files tab browses and previews workspace file contents.",
      "Documents tab queries OpenPlanner document rows with filters.",
      "Graph tab lazy-loads export only when visible.",
      "Labels tab creates, updates, deletes, applies, and removes labels.",
    ],
    stubs: [
      { kind: "component-integration", priority: "P1", name: "graph tab lazy-loads graph export once", assertion: "navigate from overview to graph and assert one /api/graph/export call" },
      { kind: "component-integration", priority: "P1", name: "labels CRUD and apply/remove update selected label view", assertion: "mock label endpoints and assert selected label/nodes refresh" },
      { kind: "ava-puppeteer-e2e", priority: "P2", name: "data documents search opens graph label workflow", assertion: "browser searches document, opens graph/labels, applies label to node" },
    ],
  },
  {
    id: "data-database-console",
    route: "/data/database",
    owner: "tsx",
    surface: "DataPage database tab",
    backend: [
      "GET /api/data/mongo/collections",
      "POST /api/data/mongo/query",
      "GET /api/data/pg/tables",
      "POST /api/data/pg/query",
      "POST /api/data/graphql",
    ],
    behavior: [
      "Database tab lists Mongo collections and SQL tables.",
      "Mongo filter/sort/projection JSON must validate before query POST.",
      "Postgres and GraphQL query panels show rows/errors without leaking credentials.",
    ],
    stubs: [
      {
        kind: "unit",
        priority: "P0",
        name: "invalid Mongo JSON blocks network call",
        assertion: "enter invalid filter and assert no POST /api/data/mongo/query",
        status: "implemented",
        implementedBy: ["frontend/src/pages/DataPage.test.ts"],
      },
      { kind: "component-integration", priority: "P1", name: "Mongo query renders rows and selected JSON detail", assertion: "mock query rows, click row, assert detail panel" },
      { kind: "component-integration", priority: "P1", name: "PG query error renders sanitized message", assertion: "mock 500 and assert message excludes connection strings" },
    ],
  },
  {
    id: "gardens-crud-public-preview",
    route: "/gardens",
    owner: "tsx",
    surface: "GardensPage",
    backend: [
      "GET /api/openplanner/v1/gardens",
      "POST /api/openplanner/v1/gardens",
      "PATCH /api/openplanner/v1/gardens/:gardenId",
      "DELETE /api/openplanner/v1/gardens/:gardenId",
      "GET /api/openplanner/v1/public/gardens/:gardenId/html",
    ],
    behavior: [
      "Garden list loads publication destinations and public preview links.",
      "Create/update/delete garden forms preserve slug/id semantics.",
      "Delete requires confirmation and refreshes the list.",
    ],
    stubs: [
      {
        kind: "component-integration",
        priority: "P1",
        name: "create garden posts form and refreshes list",
        assertion: "fill form, assert POST payload, new garden appears",
        status: "implemented",
        implementedBy: ["frontend/src/pages/GardensPage.test.tsx"],
      },
      {
        kind: "component-integration",
        priority: "P1",
        name: "delete garden asks confirmation and removes row",
        assertion: "mock confirm true/false and assert DELETE only on true",
        status: "implemented",
        implementedBy: ["frontend/src/pages/GardensPage.test.tsx"],
      },
      { kind: "ava-puppeteer-e2e", priority: "P2", name: "public preview link is generated for garden", assertion: "browser fixture asserts preview href for selected garden" },
    ],
  },
  {
    id: "translations-review-workbench",
    route: "/translations, /translations/:documentId/:targetLang",
    owner: "tsx",
    surface: "TranslationReviewPage and translation cards",
    backend: [
      "GET /api/translations/segments",
      "GET /api/translations/segments/:segmentId",
      "POST /api/translations/segments/:segmentId/labels",
      "GET /api/translations/export/manifest",
      "GET /api/translations/export/sft",
      "GET /api/translations/documents",
      "GET /api/translations/documents/:documentId/:targetLang",
      "POST /api/translations/documents/:documentId/:targetLang/review",
      "GET /api/translations/batches",
      "POST /api/translations/batches",
      "GET/PATCH /api/openplanner/v1/translations/config",
      "GET /api/proxx/models",
    ],
    behavior: [
      "Translation pages list segments/documents/batches and drill into document review.",
      "Labeling a segment or reviewing a document posts structured review payloads and updates status.",
      "Manifest/SFT export downloads are gated by selected project/language.",
      "Translation model config loads Proxx models and persists selected model.",
    ],
    stubs: [
      { kind: "component-integration", priority: "P0", name: "document review posts overall and overrides", assertion: "edit segment override and submit review payload" },
      { kind: "component-integration", priority: "P1", name: "segment label updates status and row badge", assertion: "click approve/reject, assert POST label payload and status" },
      {
        kind: "component-integration",
        priority: "P1",
        name: "model config selects Proxx model and saves PATCH",
        assertion: "mock models/config, change model, assert PATCH body",
        status: "implemented",
        implementedBy: ["frontend/src/components/admin-page/TranslationModelSection.test.tsx"],
      },
    ],
  },
  {
    id: "admin-orgs-actors-roles-lakes",
    route: "/ops/admin/*",
    owner: "tsx",
    surface: "AdminLayout overview, orgs, actors, roles, lakes tabs",
    backend: [
      "GET /api/auth/context",
      "GET /api/admin/bootstrap",
      "GET /api/admin/permissions",
      "GET /api/admin/tools",
      "GET/POST /api/admin/orgs",
      "GET/POST /api/admin/orgs/:orgId/actors",
      "PATCH /api/admin/actors/:userId",
      "PUT /api/admin/actors/:userId/credentials/:provider",
      "GET/POST /api/admin/orgs/:orgId/roles",
      "PATCH /api/admin/roles/:roleId/tool-policies",
      "PATCH /api/admin/memberships/:membershipId/roles",
      "PATCH /api/admin/memberships/:membershipId/tool-policies",
      "GET/POST /api/admin/orgs/:orgId/data-lakes",
    ],
    behavior: [
      "Admin bootstraps auth context, permissions, tools, orgs, and selected-org scoped users/roles/lakes.",
      "Create/update forms enforce permissions and refresh only scoped resources.",
      "Tool-policy editors preserve allow/deny effects for roles and memberships.",
    ],
    stubs: [
      { kind: "component-integration", priority: "P0", name: "bootstrap partial failure still renders scoped org fallback", assertion: "mock permissions/tools failure and auth context success" },
      { kind: "component-integration", priority: "P0", name: "create actor posts selected org id and roles", assertion: "fill actor form and assert /orgs/:id/actors payload" },
      { kind: "component-integration", priority: "P1", name: "membership role/tool-policy save refreshes selected org data", assertion: "toggle roles/tools and assert PATCH endpoints" },
    ],
  },
  {
    id: "admin-integrations-events-proxx-observability",
    route: "/ops/admin/integrations and admin components",
    owner: "tsx",
    surface: "DiscordSection, DataLakesSection, ProxxObservabilitySection, TranslationModelSection",
    backend: [
      "GET/PUT /api/admin/config/discord",
      "GET/PUT /api/admin/config/events",
      "POST /api/admin/config/events/jobs/:id/run",
      "POST /api/admin/config/events/dispatch",
      "POST /api/admin/config/events/runtime/start|stop|reset",
      "GET/POST/DELETE /api/ingestion/sources",
      "GET /api/ingestion/sources/:sourceId/audit",
      "GET/POST/POST cancel /api/ingestion/jobs",
      "WS /api/ingestion/ws/jobs/:jobId",
      "GET /api/proxx/observability/dashboard/overview",
      "GET /api/proxx/observability/analytics/provider-model",
      "GET /api/proxx/observability/request-logs",
      "GET/PATCH /api/openplanner/v1/translations/config",
      "GET /api/proxx/models",
    ],
    behavior: [
      "Integration panels configure Discord/events, control ingestion, monitor Proxx, and select translation model.",
      "Ingestion job websocket updates active job progress and falls back to polling on close/error.",
      "Sensitive tokens display previews only and never echo raw values after save.",
    ],
    stubs: [
      { kind: "component-integration", priority: "P0", name: "Discord token save sends raw input but renders preview only", assertion: "type token, save, assert PUT body and DOM does not contain token" },
      { kind: "ws-contract", priority: "P1", name: "ingestion websocket progress updates job card and poll fallback", assertion: "mock WS message/close and assert final GET /jobs/:id" },
      { kind: "component-integration", priority: "P1", name: "Proxx observability windows reload all analytics cards", assertion: "change window and assert all observability endpoints include new window" },
    ],
  },
  {
    id: "ops-documents-vectors-settings-graph-export",
    route: "/ops/documents, /ops/vectors, /ops/settings, /ops/graph-export-debug",
    owner: "tsx",
    surface: "DocumentsPage, VectorsPage, SettingsPage, RawGraphExportPage, SourceDocPage, SidebarOpsStatus",
    backend: [
      "GET/POST/DELETE /api/documents",
      "POST /api/documents/upload",
      "POST /api/documents/ingest",
      "POST /api/documents/ingest/restart",
      "GET /api/documents/ingestion-status",
      "GET /api/documents/ingestion-progress",
      "GET /api/documents/content/:path",
      "GET /api/documents/ingestion-history",
      "GET/PUT /api/settings",
      "GET /api/settings/knoxx-status",
      "GET/POST/PATCH/DELETE /api/settings/databases",
      "POST /api/settings/databases/activate",
      "GET /api/retrieval/stats",
      "POST /api/chat/retrieval-debug",
      "GET /api/graph/export",
    ],
    behavior: [
      "Legacy ops documents upload/delete/ingest flows preserve selected document state.",
      "Settings forms read/write app settings, database configs, and Knoxx status.",
      "Vector/retrieval and raw graph export diagnostics expose stats and downloadable data.",
    ],
    stubs: [
      { kind: "component-integration", priority: "P1", name: "documents upload then ingest updates progress", assertion: "mock upload/ingest/progress sequence and assert progress bar" },
      { kind: "component-integration", priority: "P1", name: "settings database activation posts selected id", assertion: "select database, activate, assert POST /activate payload" },
      { kind: "component-integration", priority: "P2", name: "graph export debug renders node/edge counts from export", assertion: "mock graph export and assert diagnostics" },
    ],
  },
];
