(ns devel.ui.helix.core
  "Core exports for the Helix package.

   Component wrappers track the canonical React implementation in ../dist,
   while exposing idiomatic kebab-case vars for ClojureScript consumers."
  (:require [devel.ui.helix.primitives.core :as primitives]))

(def theme-provider primitives/theme-provider)
(def toast-provider primitives/toast-provider)

(def button primitives/button)
(def badge primitives/badge)
(def spinner primitives/spinner)
(def card primitives/card)
(def card-header primitives/card-header)
(def card-body primitives/card-body)
(def card-footer primitives/card-footer)
(def modal primitives/modal)
(def modal-header primitives/modal-header)
(def modal-body primitives/modal-body)
(def modal-footer primitives/modal-footer)
(def tooltip primitives/tooltip)
(def input primitives/input)
(def select primitives/select)
(def textarea primitives/textarea)
(def progress primitives/progress)
(def resizable-pane primitives/resizable-pane)
(def which-key-popup primitives/which-key-popup)
(def inspector-pane primitives/inspector-pane)
(def context-section primitives/context-section)
(def pinned-tabs-bar primitives/pinned-tabs-bar)
(def permission-card primitives/permission-card)
(def prompt-card primitives/prompt-card)
(def permission-prompts primitives/permission-prompts)
(def react-reagent-seam primitives/react-reagent-seam)
(def command-palette primitives/command-palette)
(def chat primitives/chat)
(def toast primitives/toast)
(def file-tree primitives/file-tree)
(def tabs primitives/tabs)
(def searchable-select primitives/searchable-select)
(def collapsible-panel primitives/collapsible-panel)
(def key-value-section primitives/key-value-section)
(def surface-hero primitives/surface-hero)
(def panel-header primitives/panel-header)
(def metric-tile primitives/metric-tile)
(def metric-tile-grid primitives/metric-tile-grid)
(def filter-toolbar primitives/filter-toolbar)
(def action-strip primitives/action-strip)
(def status-chip-stack primitives/status-chip-stack)
(def data-table-shell primitives/data-table-shell)
(def pagination primitives/pagination)
(def feed primitives/feed)
(def markdown primitives/markdown)
(def code-block primitives/code-block)
(def diff-viewer primitives/diff-viewer)
(def markdown-editor primitives/markdown-editor)
(def rich-text-editor primitives/rich-text-editor)

(def use-toast primitives/use-toast)
(def use-adapter primitives/use-adapter)
(def use-uxx-theme primitives/use-uxx-theme)
(def use-resolved-theme primitives/use-resolved-theme)
(def use-theme-name primitives/use-theme-name)
(def paginate-items primitives/paginate-items)
(def calculate-total-pages primitives/calculate-total-pages)

(def components primitives/components)
(def providers primitives/providers)
(def hooks primitives/hooks)
(def utilities primitives/utilities)
