(ns eta-mu.opencode-target
  "Code generation for OpenCode plugins.

  Takes an extension spec (produced by eta-mu.core macros) and generates
  the TypeScript/JavaScript code that OpenCode expects:
  - An ESM module with Plugin export
  - tool() for tools
  - command() for commands
  - lifecycle hooks via the plugin return object"
  (:require [clojure.string :as str]))

(defn- gen-single-tool [tool]
  (let [name (:name tool)
        label (:label tool)
        desc (:description tool)
        params (:parameters tool)
        execute (:execute tool)]
    (str "const " (str/replace name #"_" "-") " = tool({\n"
         "  description: \"" desc "\",\n"
         "  args: " (pr-str params) ",\n"
         "  async execute(args, ctx) {\n"
         "    return " (pr-str execute) "\n"
         "  }\n"
         "})\n\n")))

(defn- gen-tools [tools]
  (if (empty? tools)
    ""
    (str/join "\n" (map gen-single-tool tools))))

(defn- gen-single-command [cmd]
  (let [name (:name cmd)
        desc (:description cmd)
        handler (:handler cmd)]
    (str "const " (str/replace name #"-" "_") "Cmd = command({\n"
         "  description: \"" desc "\",\n"
         "  async execute(args, ctx) {\n"
         "    return " (pr-str handler) "\n"
         "  }\n"
         "})\n\n")))

(defn- gen-commands [commands]
  (if (empty? commands)
    ""
    (str/join "\n" (map gen-single-command commands))))

(defn- gen-plugin-export [name desc]
  (str "export const " (str/replace name #"[-_]" #(str/upper-case (second %))) "Plugin: Plugin = async (ctx) => {\n"
       "  return {\n"
       "    // TODO: wire up tools and commands\n"
       "  }\n"
       "}\n"))

(defn gen-opencode-plugin [ext]
  "Generate an OpenCode plugin module from an extension spec.

  Returns a map with:
    :plugin-mjs - the ESM plugin code
    :extension-spec - metadata about the generated plugin"
  (let [name (:name ext)
        desc (:description ext)
        commands (:commands ext)
        tools (:tools ext)
        events (:events ext)]
    {:plugin-mjs (str "// Auto-generated by eta-mu build system\n"
                      "// GPL-3.0-or-later\n\n"
                      "import { Plugin } from \"@opencode-ai/plugin\"\n"
                      "import { tool, command } from \"@opencode-ai/plugin\"\n\n"
                      (gen-tools tools)
                      (gen-commands commands)
                      (gen-plugin-export name desc))
     :extension-spec {:name name
                      :description desc
                      :commands (count commands)
                      :tools (count tools)
                      :events (count events)}}))
