const sharedSecret = process.env.MCP_INTERNAL_SHARED_SECRET || "change-me-mcp-secret";
const loopbackOpenPlannerApi = process.env.OPENPLANNER_API_BASE_URL || "http://127.0.0.1:8788/api/openplanner";
const loopbackWorkspaceApi = process.env.WORKSPACE_API_BASE_URL || "http://127.0.0.1:8788/api/workspace";
const loopbackOpencodeApi = process.env.OPENCODE_API_BASE_URL || "http://127.0.0.1:8788/api/opencode";

const familyProxyEnv = (port) => ({
  NODE_ENV: "production",
  PORT: String(port),
  LEGACY_MCP_URL: process.env.LEGACY_MCP_URL || "http://127.0.0.1:4020",
  ALLOW_UNAUTH_LOCAL: process.env.ALLOW_UNAUTH_LOCAL || "true",
  MCP_INTERNAL_SHARED_SECRET: sharedSecret,
});

module.exports = {
  apps: [
    {
      name: "janus",
      script: "node",
      args: ["dist/main.js"],
      cwd: "/workspace/services/janus",
      env: {
        NODE_ENV: "production",
        API_GATEWAY_HOST: "0.0.0.0",
        API_GATEWAY_PORT: process.env.API_GATEWAY_PORT || "8788",
        OPENPLANNER_URL: process.env.OPENPLANNER_URL || "http://host.docker.internal:7777",
        OPENPLANNER_API_KEY: process.env.OPENPLANNER_API_KEY || "change-me",
        OPENCODE_URL: process.env.OPENCODE_URL || "http://opencode:4096",
        OPENCODE_USERNAME: process.env.OPENCODE_USERNAME || "opencode",
        OPENCODE_PASSWORD: process.env.OPENCODE_PASSWORD || process.env.OPENCODE_SERVER_PASSWORD || "",
        OPENCODE_API_KEY: process.env.OPENCODE_API_KEY || "",
        WORKSPACE_ROOT: process.env.WORKSPACE_ROOT || "/workspace",
        OAUTH_ENABLED: process.env.OAUTH_ENABLED || "true",
        OAUTH_ISSUER: process.env.OAUTH_ISSUER || "http://127.0.0.1:3001",
        OAUTH_AUDIENCE: process.env.OAUTH_AUDIENCE || "api-gateway",
        OAUTH_TOKEN_STRATEGY: process.env.OAUTH_TOKEN_STRATEGY || "opaque",
        OAUTH_OPAQUE_VERIFIER: process.env.OAUTH_OPAQUE_VERIFIER || "redis",
        OAUTH_OPAQUE_INTROSPECTION_URL:
          process.env.OAUTH_OPAQUE_INTROSPECTION_URL || "http://127.0.0.1:3001/internal/oauth/introspect",
        OAUTH_OPAQUE_SHARED_SECRET: process.env.OAUTH_OPAQUE_SHARED_SECRET || sharedSecret,
        OAUTH_REDIS_URL: process.env.OAUTH_REDIS_URL || "redis://redis:6379",
        OAUTH_REDIS_PREFIX: process.env.OAUTH_REDIS_PREFIX || "oauth-stable",
        ALLOWED_HOSTS:
          process.env.ALLOWED_HOSTS || "localhost,127.0.0.1,host.docker.internal,mcp-stack,.tailbe888a.ts.net",
        MCP_FS_OAUTH_URL: process.env.MCP_FS_OAUTH_URL || "http://127.0.0.1:3001",
        MCP_FS_OAUTH_DEV_URL: process.env.MCP_FS_OAUTH_DEV_URL || "http://127.0.0.1:3002",
        MCP_INTERNAL_SHARED_SECRET: sharedSecret,
        MCP_SERVICE_URLS:
          process.env.MCP_SERVICE_URLS ||
          JSON.stringify({
            "fs-oauth": "http://127.0.0.1:3001",
            files: "http://127.0.0.1:4011",
            mnemosyne: "http://127.0.0.1:4011",
            github: "http://127.0.0.1:4012",
            process: "http://127.0.0.1:4013",
            devtools: "http://127.0.0.1:4014",
            tdd: "http://127.0.0.1:4015",
            sandboxes: "http://127.0.0.1:4016",
            ollama: "http://127.0.0.1:4017",
            exec: "http://127.0.0.1:4018",
            kronos: "http://127.0.0.1:4020",
            lith: process.env.PART64_LITH_MCP_URL || "http://host.docker.internal:8787",
          }),
      },
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 5000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "mcp-fs-oauth-stable",
      script: "bun",
      args: ["run", "dist/index.js"],
      cwd: "/workspace/services/mcp-fs-oauth",
      env: {
        NODE_ENV: "production",
        PORT: process.env.MCP_FS_OAUTH_PORT || "3001",
        PUBLIC_BASE_URL:
          process.env.MCP_FS_OAUTH_PUBLIC_BASE_URL || "https://err-stealth-16-ai-studio-a1vgg.tailbe888a.ts.net",
        AUTH_LOGIN_PROVIDER: process.env.AUTH_LOGIN_PROVIDER || "github",
        OWNER_PASSWORD: process.env.OWNER_PASSWORD || "change-me",
        STORAGE_MODE: process.env.STORAGE_MODE || "local",
        ALLOW_UNAUTH_LOCAL: process.env.ALLOW_UNAUTH_LOCAL || "true",
        GITHUB_REPO_OWNER: process.env.GITHUB_REPO_OWNER || "riatzukiza",
        GITHUB_REPO_NAME: process.env.GITHUB_REPO_NAME || "devel",
        GITHUB_REPO_BRANCH: process.env.GITHUB_REPO_BRANCH || "main",
        GITHUB_REPO_TOKEN: process.env.GITHUB_REPO_TOKEN || process.env.GH_TOKEN || "",
        REDIS_URL: process.env.REDIS_URL || "redis://redis:6379",
        OAUTH_REDIS_PREFIX: process.env.OAUTH_REDIS_PREFIX || "oauth-stable",
        OAUTH_DUCKDB_OWNER: process.env.OAUTH_DUCKDB_OWNER || "true",
        OAUTH_DUCKDB_LOCK_TTL_SECONDS: process.env.OAUTH_DUCKDB_LOCK_TTL_SECONDS || "30",
        OAUTH_ACCESS_TTL_SECONDS: process.env.OAUTH_ACCESS_TTL_SECONDS || "86400",
        OAUTH_REFRESH_TTL_SECONDS: process.env.OAUTH_REFRESH_TTL_SECONDS || "2592000",
        MCP_SESSION_TTL_SECONDS: process.env.MCP_SESSION_TTL_SECONDS || "86400",
        MCP_INTERNAL_SHARED_SECRET: sharedSecret,
        OAUTH_PERSISTENCE_PATH: process.env.OAUTH_PERSISTENCE_PATH || "./data/oauth.db",
        LOCAL_ROOT: process.env.LOCAL_ROOT || "/workspace",
        OPENPLANNER_API_BASE_URL: loopbackOpenPlannerApi,
        OPENPLANNER_API_KEY: process.env.OPENPLANNER_API_KEY || "change-me",
        OPENCODE_API_BASE_URL: loopbackOpencodeApi,
        OPENCODE_API_KEY: process.env.OPENCODE_API_KEY || "",
        OPENCODE_USERNAME: process.env.OPENCODE_USERNAME || "opencode",
        OPENCODE_PASSWORD: process.env.OPENCODE_PASSWORD || process.env.OPENCODE_SERVER_PASSWORD || "",
        WORKSPACE_API_BASE_URL: loopbackWorkspaceApi,
        WORKSPACE_API_KEY: process.env.WORKSPACE_API_KEY || "",
        AUTO_APPROVE: process.env.AUTO_APPROVE || "true",
        OAUTH_GITHUB_REDIRECT_URI: process.env.OAUTH_GITHUB_REDIRECT_URI || "http://127.0.0.1:3001/auth/oauth/callback",
        GITHUB_LOGIN_CLIENT_ID: process.env.OAUTH_GITHUB_CLIENT_ID || process.env.GITHUB_LOGIN_CLIENT_ID || "",
        GITHUB_LOGIN_CLIENT_SECRET:
          process.env.OAUTH_GITHUB_CLIENT_SECRET || process.env.GITHUB_LOGIN_CLIENT_SECRET || "",
      },
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 5000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "mcp-fs-oauth-dev",
      script: "bun",
      args: ["run", "dist/index.js"],
      cwd: "/workspace/services/mcp-fs-oauth",
      env: {
        NODE_ENV: "production",
        PORT: process.env.MCP_FS_OAUTH_DEV_PORT || "3002",
        PUBLIC_BASE_URL:
          process.env.MCP_FS_OAUTH_DEV_PUBLIC_BASE_URL || "https://err-stealth-16-ai-studio-a1vgg.tailbe888a.ts.net",
        AUTH_LOGIN_PROVIDER: process.env.AUTH_LOGIN_PROVIDER || "github",
        OWNER_PASSWORD: process.env.OWNER_PASSWORD || "change-me",
        STORAGE_MODE: process.env.STORAGE_MODE || "local",
        ALLOW_UNAUTH_LOCAL: process.env.ALLOW_UNAUTH_LOCAL || "true",
        GITHUB_REPO_OWNER: process.env.GITHUB_REPO_OWNER || "riatzukiza",
        GITHUB_REPO_NAME: process.env.GITHUB_REPO_NAME || "devel",
        GITHUB_REPO_BRANCH: process.env.GITHUB_REPO_BRANCH || "main",
        GITHUB_REPO_TOKEN: process.env.GITHUB_REPO_TOKEN || process.env.GH_TOKEN || "",
        REDIS_URL: process.env.REDIS_URL || "redis://redis:6379",
        OAUTH_REDIS_PREFIX: process.env.OAUTH_REDIS_PREFIX_DEV || "oauth-dev",
        OAUTH_DUCKDB_OWNER: process.env.OAUTH_DUCKDB_OWNER_DEV || "false",
        OAUTH_DUCKDB_LOCK_TTL_SECONDS: process.env.OAUTH_DUCKDB_LOCK_TTL_SECONDS || "30",
        OAUTH_ACCESS_TTL_SECONDS: process.env.OAUTH_ACCESS_TTL_SECONDS || "86400",
        OAUTH_REFRESH_TTL_SECONDS: process.env.OAUTH_REFRESH_TTL_SECONDS || "2592000",
        MCP_SESSION_TTL_SECONDS: process.env.MCP_SESSION_TTL_SECONDS || "86400",
        MCP_INTERNAL_SHARED_SECRET: sharedSecret,
        OAUTH_PERSISTENCE_PATH: process.env.OAUTH_PERSISTENCE_PATH_DEV || "./data/oauth-dev.db",
        LOCAL_ROOT: process.env.LOCAL_ROOT || "/workspace",
        OPENPLANNER_API_BASE_URL: loopbackOpenPlannerApi,
        OPENPLANNER_API_KEY: process.env.OPENPLANNER_API_KEY || "change-me",
        OPENCODE_API_BASE_URL: loopbackOpencodeApi,
        OPENCODE_API_KEY: process.env.OPENCODE_API_KEY || "",
        OPENCODE_USERNAME: process.env.OPENCODE_USERNAME || "opencode",
        OPENCODE_PASSWORD: process.env.OPENCODE_PASSWORD || process.env.OPENCODE_SERVER_PASSWORD || "",
        WORKSPACE_API_BASE_URL: loopbackWorkspaceApi,
        WORKSPACE_API_KEY: process.env.WORKSPACE_API_KEY || "",
        AUTO_APPROVE: process.env.AUTO_APPROVE || "true",
        OAUTH_GITHUB_REDIRECT_URI: process.env.OAUTH_GITHUB_REDIRECT_URI || "http://127.0.0.1:3002/auth/oauth/callback",
        GITHUB_LOGIN_CLIENT_ID: process.env.OAUTH_GITHUB_CLIENT_ID || process.env.GITHUB_LOGIN_CLIENT_ID || "",
        GITHUB_LOGIN_CLIENT_SECRET:
          process.env.OAUTH_GITHUB_CLIENT_SECRET || process.env.GITHUB_LOGIN_CLIENT_SECRET || "",
      },
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 5000,
      restart_delay: 1000,
      max_restarts: 20,
      min_uptime: "5s",
    },
    {
      name: "kronos",
      script: "node",
      args: [
        "dist/index.js",
        "--config",
        "/workspace/orgs/riatzukiza/promethean/promethean.mcp.json",
      ],
      cwd: "/workspace/services/kronos",
      env: {
        NODE_ENV: "production",
        PORT: process.env.KRONOS_PORT || "4020",
        MCP_TRANSPORT: "http",
        MCP_ROOT_PATH: process.env.MCP_ROOT_PATH || "/workspace",
        MCP_EXEC_CONFIG:
          process.env.MCP_EXEC_CONFIG || "/workspace/orgs/riatzukiza/promethean/promethean.mcp.exec.json",
        GH_TOKEN: process.env.GH_TOKEN || process.env.GITHUB_TOKEN || "",
        GITHUB_TOKEN: process.env.GITHUB_TOKEN || process.env.GH_TOKEN || "",
      },
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 5000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "mnemosyne",
      script: "node",
      args: ["dist/main.js", "--config", "config/mcp-files.json"],
      cwd: "/workspace/services/mnemosyne",
      env: {
        NODE_ENV: "production",
        PORT: process.env.MNEMOSYNE_PORT || "4011",
        ALLOW_UNAUTH_LOCAL: process.env.ALLOW_UNAUTH_LOCAL || "true",
        MCP_INTERNAL_SHARED_SECRET: sharedSecret,
      },
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 5000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "mcp-github",
      script: "node",
      args: ["dist/main.js"],
      cwd: "/workspace/services/mcp-github",
      env: familyProxyEnv(4012),
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 5000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "mcp-process",
      script: "node",
      args: ["dist/main.js"],
      cwd: "/workspace/services/mcp-process",
      env: familyProxyEnv(4013),
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 5000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "mcp-devtools",
      script: "node",
      args: ["dist/main.js"],
      cwd: "/workspace/services/mcp-devtools",
      env: familyProxyEnv(4014),
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 5000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "mcp-tdd",
      script: "node",
      args: ["dist/main.js"],
      cwd: "/workspace/services/mcp-tdd",
      env: familyProxyEnv(4015),
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 5000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "mcp-sandboxes",
      script: "node",
      args: ["dist/main.js"],
      cwd: "/workspace/services/mcp-sandboxes",
      env: familyProxyEnv(4016),
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 5000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "mcp-ollama",
      script: "node",
      args: ["dist/main.js"],
      cwd: "/workspace/services/mcp-ollama",
      env: familyProxyEnv(4017),
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 5000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "mcp-exec",
      script: "node",
      args: ["dist/main.js"],
      cwd: "/workspace/services/mcp-exec",
      env: familyProxyEnv(4018),
      autorestart: true,
      watch: false,
      time: true,
      kill_timeout: 5000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
    },
  ],
};
